Ratings
Sameony/MirindaUI pull request #3
Opened 2022-02-07 16:40 UTC by Sameony

Added Static and basic ratings, along with different sizes.
![image](https://user-images.githubusercontent.com/80711125/152831050-8246b187-cbf5-4369-b846-9ee484d3b9f9.png)
![image](https://user-images.githubusercontent.com/80711125/152831222-f26e5cbe-5ade-49b6-847a-a95add15b4cc.png)
![image](https://user-images.githubusercontent.com/80711125/152831283-e6c331a0-7102-4b63-a115-779866317c3f.png)
![image](https://user-images.githubusercontent.com/80711125/152831335-ccecbd7e-51f7-490d-ab64-ca5570018a5e.png)
![image](https://user-images.githubusercontent.com/80711125/152831397-40aa171c-d3c6-433c-852c-e74a915b43de.png)

2022-02-07 16:50 UTC, kjais1720 requested changes

2022-02-07 16:50 UTC, kjais1720 commented on Templates/Ratings/ratings.js
> +hearts.forEach(heart => heart.addEventListener("click", ratingChange(hearts)))
The function is being invoked here, instead of being passed as a callback, so it will be called immediately upon the execution of the script, rather than being invoked when the icons are clicked

2022-02-08 07:50 UTC, kjais1720 approved these changes
All good now👍

2022-02-08 08:13 UTC, shuntzhere approved these changes
Code looks good, use Prettier to format the code and remove extra lines.

2022-02-08 08:17 UTC, merged